import {LanguageProvider} from "@/lib/LanguageContext";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <LanguageProvider>{children}</LanguageProvider>
    </html>
  )
}
